### ISSUE TITLE
Links are not working properly.

### ISSUE THREAD

**Issue by Sahill17** [RishikeshOps/DevOps-Learning-Resources#1]
There is some issue with the `Free Shell Scripting for DevOps Engineer-01`,  `Free Shell Scripting for DevOps Engineer-02`, `DevOps Real-Time Interview Questions and Answers`  and `DevOps Resume Review` Links. They aren't working properly.

**Comment by RishikeshOps** [comment]
Hey @SahilRathod17,
I have check those links all are working fine in my browser can you check again in your's.
Thank for your response : )
